<?xml version="1.0" encoding="utf-8"?><Database Name="employeeat" Class="DataSalaryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=den1.mssql8.gear.host;Initial Catalog=employeeat;User ID=employeeat" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="employeeatConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.salary" Member="salaries">
    <Type Name="salary">
      <Column Name="Position" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Salary" Member="Salary1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Bonus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Allowance" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DBonus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>